name: Setup Python

description: 'Setup environment'
runs:
  using: 'composite'

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.0"
        enable-cache: true

    - name: Set up Python
      run: uv python install
      shell: sh

    - name: Install the project
      run: uv sync --all-extras
      shell: sh
