name: CI

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run linter and type checker
        run: |
          uv run ruff format
          uv run ruff check
          uv run mypy .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: |
          uv run coverage run --source=app -m pytest
          uv run coverage report --show-missing
          uv run coverage html
